/* 将可维护的模块源文件打包为离线嵌入页，不安装依赖、不改宿主、不放宽 iframe 隔离。
   node modeling/build.cjs            生成
   node modeling/build.cjs --check    检查生成页是否与源码一致 */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'parametric');
const read=p=>{
 const file=path.resolve(root,p);
 if(!file.startsWith(root+path.sep))throw new Error('资源超出模块目录：'+p);
 return fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');
};
let html=read('index.html');
html=html.replace(/<link rel="stylesheet" href="([^"]+)"\s*\/>/g,(_,p)=>{
 const css=read(p);if(/<\/style/i.test(css))throw new Error('CSS 包含结束标签');
 return '<style>\n'+css+'\n</style>';
});
const hashes=[];
html=html.replace(/<script src="([^"]+)"><\/script>/g,(_,p)=>{
 const js='\n'+read(p)+'\n';if(/<\/script/i.test(js))throw new Error('脚本包含结束标签：'+p);
 hashes.push("'sha256-"+crypto.createHash('sha256').update(js).digest('base64')+"'");
 return '<script>'+js+'</script>';
});
if(hashes.length!==8)throw new Error('脚本依赖数量变化，请检查加载顺序并更新打包约束');
html=html.replace("script-src 'self';",'script-src '+hashes.join(' ')+';');
html='<!-- GENERATED by modeling/build.cjs. Edit source files, then rebuild. -->\n'+html;
const output=path.join(root,'embedded.html');
if(process.argv.includes('--check')){
 if(!fs.existsSync(output)||fs.readFileSync(output,'utf8')!==html)throw new Error('embedded.html 已过期，请运行 node modeling/build.cjs');
 console.log('Embedded bundle is up to date');
}else{fs.writeFileSync(output,html);console.log('Built '+output);}
