'use strict';
const crypto=require('node:crypto');
const quota=require('./ai-quota.cjs');
const PREFIX='runye:case:v1:', INDEX=PREFIX+'index';
const memory=new Map(), memoryIndex=[];
function testMode(){return process.env.NODE_ENV==='test';}
function redisCommand(command){if(testMode()){const op=command[0];if(op==='SET'){memory.set(command[1],command[2]);return Promise.resolve('OK');}if(op==='GET')return Promise.resolve(memory.get(command[1])||null);if(op==='ZADD'){if(!memoryIndex.includes(command[3]))memoryIndex.push(command[3]);return Promise.resolve(1);}if(op==='ZREVRANGE')return Promise.resolve(memoryIndex.slice().reverse());}const url=process.env.UPSTASH_REDIS_REST_URL,token=process.env.UPSTASH_REDIS_REST_TOKEN;if(!url||!token)throw Object.assign(new Error('案例库服务未配置（需要 UPSTASH_REDIS_REST_URL 与 UPSTASH_REDIS_REST_TOKEN）。'),{code:503});return fetch(url,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(10000)}).then(async r=>{const d=await r.json();if(!r.ok||d.error)throw Object.assign(new Error('案例库暂不可用。'),{code:503});return d.result;});}
function status(v){return ['deployed','pending','abandoned'].includes(v)?v:null}function source(v){return ['manual','ai'].includes(v)?v:null}
function finite(v){return typeof v==='number'&&Number.isFinite(v)}
function normalize(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('案例格式无效。');const s=source(raw.source),st=status(raw.status);if(!s||!st)throw Error('案例来源或状态无效。');const f=raw.feature||{},p=raw.plan||{},ec=raw.engine_check||{};if(!Array.isArray(p.polygon)||p.polygon.length<3||p.polygon.length>2000)throw Error('匿名地块边界无效。');if(!finite(ec.pump_head_m)||!finite(ec.pump_flow_m3h)||ec.pump_flow_m3h<=0)throw Error('案例必须先通过灌溉引擎水力校核。');const cleanPoly=p.polygon.map(q=>({x:+q.x,y:+q.y}));if(cleanPoly.some(q=>!finite(q.x)||!finite(q.y)))throw Error('匿名地块坐标无效。');return {schema_version:1,source:s,status:st,feature:{area_m2:finite(f.area_m2)?f.area_m2:null,mu:finite(f.mu)?f.mu:null,vertices:cleanPoly.length,bbox_ratio:finite(f.bbox_ratio)?f.bbox_ratio:null,terrain_dh:finite(f.terrain_dh)?f.terrain_dh:null,tape_spacing:finite(f.tape_spacing)?f.tape_spacing:null,emitter_spacing:finite(f.emitter_spacing)?f.emitter_spacing:null,emitter_flow:finite(f.emitter_flow)?f.emitter_flow:null,tape_lay_side:finite(f.tape_lay_side)?f.tape_lay_side:null,zone_mu:finite(f.zone_mu)?f.zone_mu:null},engine_check:{pump_head_m:ec.pump_head_m,pump_flow_m3h:ec.pump_flow_m3h,main_od_mm:finite(ec.main_od_mm)?ec.main_od_mm:null,branch_od_mm:finite(ec.branch_od_mm)?ec.branch_od_mm:null,front_od_mm:finite(ec.front_od_mm)?ec.front_od_mm:null,tape_delta_pct:finite(ec.tape_delta_pct)?ec.tape_delta_pct:null},plan:{polygon:cleanPoly,input_values:p.input_values||{},pipe_plan:p.pipe_plan||null,pipe_od_override:p.pipe_od_override||null,iso_diagram:p.iso_diagram||null,tl_auto_edits:p.tl_auto_edits||null,tl_edit_pipes:p.tl_edit_pipes||null,manual_groups:Array.isArray(p.manual_groups)?p.manual_groups:[]},feedback:{rating:Math.max(0,Math.min(5,Number(raw.feedback&&raw.feedback.rating)||0)),note:String(raw.feedback&&raw.feedback.note||'').slice(0,500)}};}
function rank(c,q){const f=c.feature||{},a=Math.abs((f.area_m2||0)-(q.area||0))/Math.max(1,q.area||1),r=Math.abs((f.bbox_ratio||1)-(q.ratio||1));return (c.source==='manual'?100:40)+(c.status==='deployed'?80:0)+(c.feedback.rating||0)*3-Math.min(60,a*60)-Math.min(15,r*8);}
async function submit(req,raw){const account=quota.identity(req),c=normalize(raw),id=crypto.randomUUID(),now=new Date().toISOString();c.id=id;c.created_at=now;c.updated_at=now;c.owner_hash=account;await redisCommand(['SET',PREFIX+id,JSON.stringify(c),'EX',String(60*60*24*365*3)]);await redisCommand(['ZADD',INDEX,String(Date.now()),id]);return{id};}
async function retrieve(q){const ids=await redisCommand(['ZREVRANGE',INDEX,'0','199']);const rows=[];for(const id of ids||[]){const raw=await redisCommand(['GET',PREFIX+id]);if(!raw)continue;try{const c=JSON.parse(raw);if(c.status==='abandoned')continue;rows.push(c);}catch{}}
return rows.sort((a,b)=>rank(b,q)-rank(a,q)).slice(0,3).map(c=>({source:c.source,status:c.status,feature:c.feature,engine_check:c.engine_check,design:{input_values:c.plan.input_values,pipe_od_override:c.plan.pipe_od_override,manual_groups:c.plan.manual_groups},rating:c.feedback.rating}));}
module.exports={submit,retrieve,normalize,rank,_reset:()=>{memory.clear();memoryIndex.length=0;}};
